services: mongodb
language: node_js
node_js:
  - "10.5"

# make mongodb a replica set
before_script:
  - mongo --version
  - echo "replication:" | sudo tee -a /etc/mongod.conf
  - |-
    echo "  replSetName: \"rs0\"" | sudo tee -a /etc/mongod.conf
  - sudo service mongod restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15

script:
  - npm run lint
  - npm run test
